services:
  backend:
    build:
      context: ./qwi-tix-server
      dockerfile: qwi-tix-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_network

  frontend:
    build:
      context: ./qwi-tix
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro 
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - frontend
      - backend

networks:
  app_network:
    driver: bridge
